spring:
  application:
    name: ${APPLICATION_NAME}
  main:
    allow-bean-definition-overriding: true
server:
  port: ${DEMO_PORT}

tracing:
  shop:
    url: ${DEMO_SHOP_URL}
  storage:
    url: ${DEMO_STORAGE_URL}
  factory:
    url: ${DEMO_FACTORY_URL}

opentracing:
  jaeger:
    udp-sender:
      host: ${OPENTRACING_HOST}
      port: ${OPENTRACING_PORT}