version: "3.7"
services:
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "5778:5778"
      - "16686:16686"
    networks:
      - simulation

  tracing-consumer:
    container_name: tracing-consumer
    image: tracing-consumer:latest
    depends_on:
      - jaeger
    environment:
#      JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,address=*:9999,suspend=y"
      APPLICATION_NAME: "docker_tracing_consumer"
      DEMO_PORT: 8091
      OPENTRACING_HOST: jaeger
      OPENTRACING_PORT: 6831
    ports:
      - "8091:8091"
      - "9999:9999"
    networks:
    - simulation

  tracing-producer:
    container_name: tracing-producer
    image: tracing-producer:latest
    depends_on:
    - jaeger
    - tracing-consumer
    environment:
      APPLICATION_NAME: "docker_tracing_producer"
      DEMO_PORT: 8092
      DEMO_CONSUMER_URL: "http://tracing-consumer:8091"
      OPENTRACING_HOST: jaeger
      OPENTRACING_PORT: 6831
    ports:
      - "8092:8092"
    networks:
      - simulation

networks:
  simulation:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv4: "true"

